steps:
- name: 'gcr.io/cloud-builders/mvn:3.5.0-jdk-8'
  args: ['package']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/petclinic:$REVISION_ID', '-t', "gcr.io/$PROJECT_ID/petclinic:latest", '.']
images: ['gcr.io/$PROJECT_ID/petclinic:latest']
